name: Run tests

on:
  push:
    branches:
      - main

env:
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_ENDPOINT: https://testing.testops.cloud/
  ALLURE_PROJECT_ID: 15030
  ALLURE_RESULTS: allure-results

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install and configure allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
          allure-token: ${{ secrets.ALLURE_TOKEN }}
          allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

      - name: Run tests with Allure
        run: |
          allurectl watch -- mvn test

      - name: Save TR as files
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ github.run_id }}
          path: ${{ env.ALLURE_RESULTS }}
          retention-days: 1
